# Dockerfile

# Use the official Node.js image as a base image
FROM node:22-alpine

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies inside the container
RUN npm install -g pnpm
RUN pnpm install -f

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Default command to start the app
CMD ["npx", "nodemon", "--legacy-watch", "src/app/server.ts"]
